### ISSUE TITLE
Does this code handle packed / compressed fields (COMP-3) conversion and copybooks?

### ISSUE THREAD

**Issue by hp2017** [tmalaska/CopybookInputFormat#4]
Hi @tmalaska ,

Apologies in advance if this is irrelevant or not the right place or way to do this and causes any inconvenience.

I am currently looking for a Java application / library that can convert an EBCDIC formatted file (from Mainframe) into standard ASCII format. I came across this code base and found it really interesting. I was wondering if this application also handles packed / compressed fields (COMP-3) conversion and copybooks?

Awaiting a prompt response.

Thanks in advance.

Kind Regards,
Harish

**Comment by tmalaska** [comment]
I belive everything by variable length.. I haven’t touched the code in a long time.. In the end it is anything that JRocket can handle.

**Comment by hp2017** [comment]
Hi @tmalaska ...sorry for the delay. Thanks a lot for the response. Kind Regards
